export default [
  {
    path: 'https://github.com/ant-design/ant-design-pro-layout/issues',
    name: 'site',
    icon: {
      type: {},
      key: null,
      ref: null,
      props: {},
      _owner: null,
      _store: {},
    },
    locale: '',
    target: '_blank',
    exact: true,
    key: 'https://github.com/ant-design/ant-design-pro-layout/issues',

    pro_layout_parentKeys: ['/'],
  },
  {
    path: 'https://baidu.com/#test',
    name: 'baidu',
    icon: {
      type: {},
      key: null,
      ref: null,
      props: {},
      _owner: null,
      _store: {},
    },
    locale: '',
    target: '_blank',
    exact: true,
    key: 'https://baidu.com/#test',

    pro_layout_parentKeys: ['/'],
  },
  {
    path: '/flex',
    name: 'flex 布局测试',
    icon: {
      type: {},
      key: null,
      ref: null,
      props: {},
      _owner: null,
      _store: {},
    },
    exact: true,
    locale: 'menu.flex 布局测试',
    key: '/flex',

    pro_layout_parentKeys: ['/'],
  },
  {
    path: '/dashboardanalysis',
    name: '分析页',
    icon: {
      type: {},
      key: null,
      ref: null,
      props: {},
      _owner: null,
      _store: {},
    },
    exact: true,
    locale: 'menu.分析页',
    key: '/dashboardanalysis',

    pro_layout_parentKeys: ['/'],
  },
  {
    path: '/accountsettings',
    name: '个人设置',
    icon: {
      type: {},
      key: null,
      ref: null,
      props: {},
      _owner: null,
      _store: {},
    },
    exact: true,
    locale: 'menu.个人设置',
    key: '/accountsettings',

    pro_layout_parentKeys: ['/'],
  },
  {
    path: '/formadvancedform',
    name: '高级表单',
    icon: {
      type: {},
      key: null,
      ref: null,
      props: {},
      _owner: null,
      _store: {},
    },
    exact: true,
    locale: 'menu.高级表单',
    key: '/formadvancedform',

    pro_layout_parentKeys: ['/'],
  },
  {
    path: '/single',
    name: 'Single',
    routes: [
      {
        path: '/single/welcome',
        name: 'two',

        locale: 'menu.Single.two',
        key: '/single/welcome',
        icon: {
          type: {},
          key: null,
          ref: null,
          props: {},
          _owner: null,
          _store: {},
        },
        exact: true,
        pro_layout_parentKeys: ['/', '/single'],
      },
      {
        path: '/single/welcome2',
        name: 'two2',

        locale: 'menu.Single.two2',
        key: '/single/welcome2',
        icon: {
          type: {},
          key: null,
          ref: null,
          props: {},
          _owner: null,
          _store: {},
        },
        exact: true,
        pro_layout_parentKeys: ['/', '/single'],
      },
    ],
    locale: 'menu.Single',
    key: '/single',
    pro_layout_parentKeys: ['/'],
  },
  {
    path: '/',
    name: 'welcome',
    icon: {
      type: {},
      key: null,
      ref: null,
      props: {},
      _owner: null,
      _store: {},
    },
    routes: [
      {
        path: '/welcome',
        name: 'one',
        icon: {
          type: {},
          key: null,
          ref: null,
          props: {},
          _owner: null,
          _store: {},
        },
        locale: 'menu.welcome.one',
        key: '/welcome',
        routes: [
          {
            path: '/welcome/repertoryFw',
            name: 'two',
            icon: {
              type: {},
              key: null,
              ref: null,
              props: {},
              _owner: null,
              _store: {},
            },

            locale: 'menu.welcome.one.two',
            key: '/welcome/repertoryFw',
            exact: true,
            pro_layout_parentKeys: ['/', 'welcome', '/welcome'],
          },
          {
            path: '/welcome/repertory',
            name: 'two2',
            icon: {
              type: {},
              key: null,
              ref: null,
              props: {},
              _owner: null,
              _store: {},
            },

            locale: 'menu.welcome.one.two2',
            key: '/welcome/repertory',
            exact: true,
            pro_layout_parentKeys: ['/', 'welcome', '/welcome'],
          },
        ],
        pro_layout_parentKeys: ['/', 'welcome'],
      },
    ],
    locale: 'menu.welcome',
    key: 'welcome',
    pro_layout_parentKeys: ['/'],
  },
];
